### PR TITLE
Use ``inspect`` to deterministically tokenize local/lambda functions

### PR DESCRIPTION
**Pull request by rjzamora**
Possible/partial solution to https://github.com/dask-contrib/dask-expr/pull/765

This is for demonstration purposes - Needs further testing/discussion.

### CODE REVIEW

**Comment by fjetter** [comment]
I was using / trying to use this before over in https://github.com/dask/dask/pull/10808 but rejected the idea again. Sorry, I don't even remember why but something was missing.

One thing I remember is that inspect just fails at times

**Comment by mrocklin** [comment]
Lambdas can also contain other important scope, like closed-over variables.

**Comment by fjetter** [comment]
the most recent commit on main of cloudpickle (not released yet) likely solves the lambda problem but there are still cases that are not handled well.

**Comment by rjzamora** [comment]
>Lambdas can also contain other important scope, like closed-over variables.

Totally agree with this. However, I'm still curious how much this matters for the tokenization purpose needed in dask-expr. (I'm sure we can come up with cases that demonstrate a problem, but I couldn't immediately imagine an obvious problem)

**Pull request closed without merging**
