### PR TITLE
Fix equality comparison of scalars with expressions

### PR DESCRIPTION
**Pull request by phofl**
cc @mrocklin 

This is one potential approach that we could. We would have to remove every other binary op from Expr as well, since, ``2 < df.expr`` is still True.

The alternative would be to raise for ``bool(Expr)``, which might make more sense, although we couldn't use Expressions in Sets or as dictionary keys anymore. ``bool(DaskDataFrame)`` raises as well

### CODE REVIEW

**Comment by mrocklin** [comment]
I don't have a strong opinion here yet.  Do you?

**Comment by phofl** [comment]
No not a strong opinion at this moment.

I think making ``bool(Expr)`` raise gives us more stability guarantees in the future but it will be annoying to deal with in the beginning

**Comment by mrocklin** [comment]
I'm fine with having `bool(expr)` raise.  I guess this lets us continue to use binary relational operators.  

Are there cases today where we want to use expressions in sets and dicts?  That's probably relevant to help make this decision.

**Comment by phofl** [comment]
There are cases where we are using them but I think that's not a good idea there. expr._name is a better choice in most cases I think

**Comment by phofl** [comment]
#307

**Pull request closed without merging**
