### PR TITLE
Handle shuffle method name for upcoming ``dask`` release

### PR DESCRIPTION
**Pull request by jrbourbeau**
This method will change names in the upcoming `dask` release next week (xref https://github.com/dask/dask/pull/10344). Handling that name change early here.

### CODE REVIEW

**Comment by phofl** [comment]
Personally, I'd prefer not adding too many of these version consistency things at this stage. I am happy as long as we are compliant with the latest Dask release until we are in a more mature state.

**Comment by rjzamora** [comment]
@phofl makes a reasonable point. We don't really have "users" yet. So, perhaps it's best to test against `main` and simply fix breakages like this as they show up?

**Comment by phofl** [comment]
I'd rather test against the latest release, this makes running benchmarks and stuff a bit easier without having to install from main all the time. We release all 2 weeks in dask, so this shouldn't be too bad?

**Comment by rjzamora** [comment]
I wouldn't want to make benchmarking too tricky.

I was just thinking that it becomes tricky to use `dask:main` with `dask-expr:main` (something I personally do often) if we  fix breakages after a dask release.

One possibility is to follow the convention used in this PR, but to immediately raise an issue to remove the `try`/`except` after the next release?

**Comment by phofl** [comment]
Then let's go with main, my opinion isn't strong here.

**Comment by rjzamora** [comment]
>Then let's go with main, my opinion isn't strong here.

I pushed a commit to move to `main`. I also don't have super strong opinions about this, so we can always move back to the latest release (or agree to handle both `main` and the latest release).

**Review by rjzamora — APPROVED** [review]
Thanks @jrbourbeau

I'll merge this now, and we can change our stance if relying on `main` causes problems.

**Pull request merged**
